name: Repository Size

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  repository-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display branch name
        run: echo "Current branch: ${{ github.ref }}"
      - name: Check repository size
        run: du -skh --exclude=".git" .
